### ISSUE TITLE
Replace x86_64 instructions.

### ISSUE THREAD

**Issue by ryaangu** [strawberryhacker/luxury#3]
What if you replace:
```s
mov %rbp, %rsp
pop %rbp
```
with 
```s
leave
```
It's just one byte and also faster.

**Comment by strawberryhacker** [comment]
Hi, thank you for taking time to review the code.

I did not know about the enter / leave instruction. I want to support local function, for which I will need to save pointers to previous stack frames. However, I don't know if I will do it the way Intel does it. If I end up with a custom stack layout I cannot use the enter instruction. This will also force me to add some instructions befor the leave - so I do not know if the leave will be harder to read. 

Anyway, this will be implemented later, but for now it is a good idea, so I will add it.

Again, thanks for reviwing the code.

**Comment by ryaangu** [comment]
Okay! I said about the `leave` instruction because it's faster than `mov %rbp, %rsp ` and `pop %rbp`. Now about the `enter` instruction, it's faster to keep the default way.

**Comment by strawberryhacker** [comment]
I read myself up on that topic and it seems you are absolutely correct. The enter is slower and the leave is faster. So it was a good suggestion, and I will do it so.

Thank you.
